### ISSUE TITLE
Errors at debug/release

### ISSUE THREAD

**Issue by keoshi122** [semihcevik/hwidspoofer#1]
When i try to build the spoofer i get some errors , even if i am on release or debug.
![Capture](https://user-images.githubusercontent.com/88397500/128058442-772037c7-0949-4d6e-a012-7fabfa831630.PNG)
![Capture2](https://user-images.githubusercontent.com/88397500/128058530-738b320a-17de-4b55-ae95-d138e640b67a.PNG)

**Comment by semihcevik** [comment]
Check project settings

**Comment by keoshi122** [comment]
> Check project settings

What do i need to check in there?

**Comment by bytes1337** [comment]
@keoshi122  pasting moment

**Comment by FishyFishsEatingFishs** [comment]
its a dll? so when will the imgui show up? when you map the dll? how would you map a dll?

**Comment by FishyFishsEatingFishs** [comment]
never mind i figured it out.

**Comment by FishyFishsEatingFishs** [comment]
it creates a file from memory from bytes but what bytes are for the driver, mapper etc

**Comment by FishyFishsEatingFishs** [comment]
cant people just grab the files when you create them from memory i think its still grabbable
